import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_component/Navbar/Navbar";
import Footer from './_component/Footer/Footer';
import '@fortawesome/fontawesome-free/css/all.css'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Toaster } from "@/components/ui/sonner"

import UserSessionProvider from "./UserSessionProvider";
import CountProvider from "src/context/CountContext";
const Encode_SansFont = Encode_Sans({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Encode_SansFont.className}`}
      >
        <UserSessionProvider>
          <CountProvider>
            <Navbar />
            <main className="p-5 ">

              {children}
            </main>

            <Toaster />
            <Footer />
          </CountProvider>
        </UserSessionProvider>
      </body>
    </html>
  );
}
